# Generated by Django 5.0.6 on 2024-05-27 15:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce_app', '0002_classifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='product_images/'), size=None)),
                ('sizes_available', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECommerce_app.classifications')),
            ],
        ),
    ]
