# Generated by Django 5.0.6 on 2024-05-28 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce_app', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None),
        ),
    ]
