# Generated by Django 5.0.6 on 2024-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce_app', '0004_alter_products_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
