# Generated by Django 5.0.6 on 2024-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce_app', '0005_remove_products_images_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
