# Generated by Django 5.0.3 on 2024-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce_app', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.TextField(default='', max_length=255),
        ),
    ]
