# Generated by Django 5.0.3 on 2024-06-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce_app', '0009_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
